# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20180406_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='default description placeholder'),
            preserve_default=False,
        ),
    ]
