# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180411_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
